1d_binning:
  NBINS: 291
  NMAX: 290
  NMIN: 0
1d_bootstrap:
  NBOOT: 10
  NWORKERS: 8
1d_phi_ensemble:
  PEAK_CUT: 100
  PHI_BINS: 991
  PHI_BIN_MAX: -2.47
  PHI_BIN_MIN: 7.43
1d_phi_star:
  PHI_STAR: -0.11
  PHI_STAR_COEX: -0.11199
  PHI_STAR_EQ: -0.09579
  PLOT_PHI_STAR_BETAF_MAX: 6
  PLOT_PHI_STAR_N_MAX: 225
  PLOT_PHI_STAR_N_MIN: 105
2d_binning:
  NBINS2: 283
  NMAX2: 282
  NMIN2: 0
  RGBINS2: 61
  RGMAX2: 16.565656565656568
  RGMIN2: 4.444444444444445
2d_phi_star:
  PHI_STAR2: -0.11
  PHI_STAR_COEX2: -0.11199
  PHI_STAR_EQ2: -0.09579
2d_plot:
  PLOT_BETAF_LEVELS2: 22
  PLOT_BETAF_MAX2: 168
  PLOT_N_MAX2: 282
  PLOT_N_MIN2: 0
  PLOT_PV_LEVELS2: 22
2d_plot_phi_star:
  PLOT_PHI_STAR_BETAF_LEVELS2: 11
  PLOT_PHI_STAR_BETAF_MAX2: 6
  PLOT_PHI_STAR_N_MAX2: 225
  PLOT_PHI_STAR_N_MIN2: 105
  PLOT_PHI_STAR_PV_LEVELS2: 11
  PLOT_PHI_STAR_RG_MAX2: 14.6
  PLOT_PHI_STAR_RG_MIN2: 4.6
basins:
  NC: 131
  NE: 203
coex:
  NT_SPLIT: 175
coex2:
  NTRG_SPLIT_c: null
  NTRG_SPLIT_m: null
  NTRG_SPLIT_x0: null
coexRg:
  RG_SPLIT: null
data_collection:
  BASE_SAMP_FREQ: 1
  BASE_SAMP_FREQ2: 1
  TEND: null
  TSTART: 2000
find_basins:
  NC_MAX: 140
  NC_MIN: 120
  NE_MAX: 210
  NE_MIN: 190
func_params:
  calc_deltaGu_diff_method:
    boot_errors: false
    deltaGu_datfile: deltaGu_diff.dat
  calc_deltaGu_int_method_1D:
    deltaGu_datfile: deltaGu_int.dat
  plot_hist:
    hist_imgfile: hist.png
  run_binless_log_likelihood:
    betaF_datfile: betaF.dat
    betaF_imgfile: betaF.png
    calcfile: calc.pkl
    prob_datfile: prob.dat
    prob_imgfile: prob.png
  run_bootstrap_ll_phi_ensemble:
    betaFboot_datfile: betaF_boot.dat
    betaFboot_imgfile: betaF_boot.png
    phi_ens_boot_datfile: phi_ens_boot.dat
    phi_ens_boot_imgfile: phi_ens_boot.png
    phi_ens_peaks_boot_datfile: phi_ens_peaks_boot.dat
  run_kappa_checks:
    imgfile: curvature_kappa.png
    in_calcfile: calc.pkl
    saved: true
  run_phi_c_star_opt:
    betaFrew_datfile: betaF_phi_c_star.dat
    betaFrew_imgfile: betaF_phi_c_star.png
    in_calcfile: calc.pkl
    opt_thresh: 0.0001
    probrew_datfile: prob_phi_c_star.dat
    probrew_imgfile: prob_phi_c_star.png
    saved: true
  run_phi_e_star_opt:
    betaFrew_datfile: betaF_phi_e_star.dat
    betaFrew_imgfile: betaF_phi_e_star.png
    in_calcfile: calc.pkl
    opt_thresh: 0.0001
    probrew_datfile: prob_phi_e_star.dat
    probrew_imgfile: prob_phi_e_star.png
    saved: true
  run_phi_ensemble_reweight:
    in_calcfile: calc.pkl
    phi_ens_datfile: phi_ens.dat
    phi_ens_imgfile: phi_ens.png
    phi_ens_peaks_datfile: phi_ens_peaks.dat
    saved: true
  run_reweight_phi_1_star:
    betaFrew_datfile: betaF_phi_1_star.dat
    betaFrew_imgfile: betaF_phi_1_star.png
    in_calcfile: calc.pkl
    probrew_datfile: prob_phi_1_star.dat
    probrew_imgfile: prob_phi_1_star.png
    saved: true
  run_reweighting_checks:
    KLD_imgfile: KLD.png
    KLD_thresh: 0.1
    in_calcfile: calc.pkl
    saved: true
    win_dir: windows
    win_format: betaF_biased_win_{}.png
  run_2D_binless_log_likelihood:
    saved: True
    in_calcfile: calc.pkl
    calcfile: calc_2D.pkl
    betaF_imgfile: betaF_2D.png
    x_bins_npyfile: x_bins_2D.npy
    y_bins_npyfile: y_bins_2D.npy
    betaF_npyfile: betaF_2D.npy
    prob_imgfile: prob_2D.png
    prob_npyfile: prob_2D.npy
  run_2D_bin_Rg:
    saved: True
    in_calcfile: calc.pkl
    betaF_datfile: betaF_Rg.dat
    betaF_imgfile: betaF_Rg.png
    prob_datfile: prob_Rg.dat
    prob_imgfile: prob_Rg.png
  run_2D_reweight_phi_star:
    saved: True
    in_calcfile: calc.pkl
    betaF_imgformat: betaF_2D_{}.png
    x_bins_npyformat: x_bins_2D_{}.npy
    y_bins_npyformat: y_bins_2D_{}.npy
    betaF_npyformat: betaF_2D_{}.npy
    prob_imgformat: prob_2D_{}.png
    prob_npyformat: prob_2D_{}.npy
  run_2D_reweight_phi_star_bin_Rg:
    saved: True
    in_calcfile: calc.pkl
    betaF_datfile: betaF_Rg_{}.dat
    betaF_imgfile: betaF_Rg_{}.png
    prob_datfile: prob_Rg_{}.dat
    prob_imgfile: prob_Rg_{}.png
io_global:
  calcoutdir: wham_nt_ntrg_test_data/calc
  plotoutdir: wham_nt_ntrg_test_data/plot
system:
  NBEAD: 45
  TEMP: 298
umbrellas:
  KAPPA: 0.0243
windows:
  unbiased:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/unbiased/nt_ntw_k0_N0.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/unbiased/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 100
    XTCDT: 100
  -240:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-240/ntw_k0.0243_N-240.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-240/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -220:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-220/ntw_k0.0243_N-220.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-220/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -200:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-200/ntw_k0.0243_N-200.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-200/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -180:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-180/ntw_k0.0243_N-180.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-180/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -160:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-160/ntw_k0.0243_N-160.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-160/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -140:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-140/ntw_k0.0243_N-140.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-140/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -120:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-120/ntw_k0.0243_N-120.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-120/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -100:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-100/ntw_k0.0243_N-100.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-100/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -80:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-80/ntw_k0.0243_N-80.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-80/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -60:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-60/ntw_k0.0243_N-60.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-60/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -40:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-40/ntw_k0.0243_N-40.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-40/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  -20:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N-20/ntw_k0.0243_N-20.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N-20/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  0:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N0/ntw_k0.0243_N0.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N0/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  20:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N20/ntw_k0.0243_N20.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N20/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  40:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N40/ntw_k0.0243_N40.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N40/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  60:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N60/ntw_k0.0243_N60.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N60/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  80:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N80/ntw_k0.0243_N80.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N80/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  100:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N100/ntw_k0.0243_N100.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N100/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  120:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N120/ntw_k0.0243_N120.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N120/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  140:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N140/ntw_k0.0243_N140.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N140/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  160:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N160/ntw_k0.0243_N160.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N160/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  180:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N180/ntw_k0.0243_N180.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N180/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  200:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N200/ntw_k0.0243_N200.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N200/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  220:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N220/ntw_k0.0243_N220.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N220/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  240:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N240/ntw_k0.0243_N240.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N240/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  260:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N260/ntw_k0.0243_N260.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N260/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  280:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N280/ntw_k0.0243_N280.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N280/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  300:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N300/ntw_k0.0243_N300.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N300/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  320:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N320/ntw_k0.0243_N320.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N320/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  340:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N340/ntw_k0.0243_N340.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N340/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  360:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N360/ntw_k0.0243_N360.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N360/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  380:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N380/ntw_k0.0243_N380.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N380/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  400:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N400/ntw_k0.0243_N400.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N400/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  420:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N420/ntw_k0.0243_N420.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N420/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  440:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N440/ntw_k0.0243_N440.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N440/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  460:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N460/ntw_k0.0243_N460.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N460/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  480:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N480/ntw_k0.0243_N480.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N480/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  500:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N500/ntw_k0.0243_N500.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N500/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  520:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N520/ntw_k0.0243_N520.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N520/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  540:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N540/ntw_k0.0243_N540.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N540/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  560:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N560/ntw_k0.0243_N560.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N560/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
  580:
    Nt_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298/K0.0243/K0.0243N580/ntw_k0.0243_N580.dat
    Rg_file: inputs_ensemble.polymer.wham_nt_ntrg/C45_T298_OP/K0.0243/K0.0243N580/C45_Rg.pkl
    TSTEP: 0.002
    UMBDT: 50
    XTCDT: 100
