system:
  NBEAD: ~
  TEMP: ~

umbrellas:
  KAPPA: ~

windows: ~

data_collection:
  TSTART: 0
  TEND: ~
  BASE_SAMP_FREQ: 1
  BASE_SAMP_FREQ2: 1

1d_binning:
  NMIN: 0
  NMAX: ~
  NBINS: ~

1d_bootstrap:
  NBOOT: 10
  NWORKERS: 8

1d_phi_ensemble:
  PHI_BIN_MIN: ~
  PHI_BIN_MAX: ~
  PHI_BINS: ~
  PEAK_CUT: ~

1d_phi_star:
  PHI_STAR: ~
  PHI_STAR_EQ: ~
  PHI_STAR_COEX: ~
  PLOT_PHI_STAR_N_MIN: ~
  PLOT_PHI_STAR_N_MAX: ~
  PLOT_PHI_STAR_BETAF_MAX: ~

2d_binning:
  NMIN2: 0
  NMAX2: ~
  NBINS2: ~
  RGMIN2: 0
  RGMAX2: ~
  RGBINS2: ~

2d_plot:
  PLOT_N_MIN2: ~
  PLOT_N_MAX2: ~
  PLOT_BETAF_MAX2: ~
  PLOT_BETAF_LEVELS2: ~
  PLOT_PV_LEVELS2: ~

2d_phi_star:
  PHI_STAR2: ~
  PHI_STAR_EQ2: ~
  PHI_STAR_COEX2: ~

2d_plot_phi_star:
  PLOT_PHI_STAR_N_MIN2: ~
  PLOT_PHI_STAR_N_MAX2: ~
  PLOT_PHI_STAR_RG_MIN2: ~
  PLOT_PHI_STAR_RG_MAX2: ~
  PLOT_PHI_STAR_BETAF_MAX2: ~
  PLOT_PHI_STAR_BETAF_LEVELS2: ~
  PLOT_PHI_STAR_PV_LEVELS2: ~

coex:
  NT_SPLIT: ~

coex2:
  RG_SPLIT: ~
  NTRG_SPLIT_m: ~
  NTRG_SPLIT_x0: ~
  NTRG_SPLIT_c: ~

find_basins:
  NC_MIN: ~
  NC_MAX: ~
  NE_MIN: ~
  NE_MAX: ~

basins:
  NC: ~
  NE: ~

io_global:
  calcoutdir: ~
  plotoutdir: ~

func_params:
  plot_hist:
    hist_imgfile: hist.png
  run_binless_log_likelihood:
    calcfile: calc.pkl
    betaF_datfile: betaF.dat
    betaF_imgfile: betaF.png
    prob_datfile: prob.dat
    prob_imgfile: prob.png
  run_kappa_checks:
    saved: True
    in_calcfile: calc.pkl
    imgfile: curvature_kappa.png
  run_reweighting_checks:
    saved: True
    in_calcfile: calc.pkl
    win_dir: windows
    win_format: betaF_biased_win_{}.png
    KLD_thresh: 0.1
    KLD_imgfile: KLD.png
  run_phi_ensemble_reweight:
    saved: True
    in_calcfile: calc.pkl
    phi_ens_datfile: phi_ens.dat
    phi_ens_imgfile: phi_ens.png
    phi_ens_peaks_datfile: phi_ens_peaks.dat
  run_reweight_phi_1_star:
    saved: True
    in_calcfile: calc.pkl
    betaFrew_datfile: betaF_phi_1_star.dat
    betaFrew_imgfile: betaF_phi_1_star.png
    probrew_datfile: prob_phi_1_star.dat
    probrew_imgfile: prob_phi_1_star.png
  find_basins: ~
  run_phi_e_star_opt:
    saved: True
    in_calcfile: calc.pkl
    opt_thresh: 1.0e-5
    betaFrew_datfile: betaF_phi_e_star.dat
    betaFrew_imgfile: betaF_phi_e_star.png
    probrew_datfile: prob_phi_e_star.dat
    probrew_imgfile: prob_phi_e_star.png
  calc_deltaGu_diff_method:
    boot_errors: False
    deltaGu_datfile: deltaGu.dat
  coex_Nt: ~
  run_phi_c_star_opt:
    saved: True
    in_calcfile: calc.pkl
    betaFrew_datfile: betaF_phi_c_star.dat
    betaFrew_imgfile: betaF_phi_c_star.png
    probrew_datfile: prob_phi_c_star.dat
    probrew_imgfile: prob_phi_c_star.png
  calc_deltaGu_int_method_1D: ~
  run_bootstrap_ll_phi_ensemble:
    betaFboot_datfile: betaF_boot.dat
    betaFboot_imgfile: betaF_boot.png
    phi_ens_boot_datfile: phi_ens_boot.dat
    phi_ens_boot_imgfile: phi_ens_boot.png
    phi_ens_peaks_boot_datfile: phi_ens_peaks_boot.dat
