"""
Generate GRO from polymer PDB generated by Avogadro.
"""
import argparse
import MDAnalysis as mda

parser = argparse.ArgumentParser()
parser.add_argument("pdbname", help="PDB file name/path")
parser.add_argument("-o", default="out.gro", help="output file [default=out.gro]")

args = parser.parse_args()

u = mda.Universe(args.pdbname)
alk = u.atoms
alk.write(args.o)
